# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MetadataWidgetSetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MetadataWidgetSetting(object):
    def setupUi(self, MetadataWidgetSetting):
        MetadataWidgetSetting.setObjectName("MetadataWidgetSetting")
        MetadataWidgetSetting.resize(400, 204)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        MetadataWidgetSetting.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(MetadataWidgetSetting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(MetadataWidgetSetting)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.api_comboBox = QtWidgets.QComboBox(MetadataWidgetSetting)
        self.api_comboBox.setObjectName("api_comboBox")
        self.api_comboBox.addItem("")
        self.api_comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.api_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.is_download_lrc_checkBox = QtWidgets.QCheckBox(MetadataWidgetSetting)
        self.is_download_lrc_checkBox.setObjectName("is_download_lrc_checkBox")
        self.verticalLayout.addWidget(self.is_download_lrc_checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(MetadataWidgetSetting)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.auto_button = QtWidgets.QPushButton(MetadataWidgetSetting)
        self.auto_button.setObjectName("auto_button")
        self.horizontalLayout_2.addWidget(self.auto_button)
        self.label_2 = QtWidgets.QLabel(MetadataWidgetSetting)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(379, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.sure_button = QtWidgets.QPushButton(MetadataWidgetSetting)
        self.sure_button.setObjectName("sure_button")
        self.horizontalLayout.addWidget(self.sure_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(MetadataWidgetSetting)
        QtCore.QMetaObject.connectSlotsByName(MetadataWidgetSetting)

    def retranslateUi(self, MetadataWidgetSetting):
        _translate = QtCore.QCoreApplication.translate
        MetadataWidgetSetting.setWindowTitle(_translate("MetadataWidgetSetting", "Form"))
        self.label.setText(_translate("MetadataWidgetSetting", "元数据来源："))
        self.api_comboBox.setItemText(0, _translate("MetadataWidgetSetting", "网易云api"))
        self.api_comboBox.setItemText(1, _translate("MetadataWidgetSetting", "酷狗api"))
        self.is_download_lrc_checkBox.setText(_translate("MetadataWidgetSetting", "补全同时下载歌词"))
        self.checkBox_2.setText(_translate("MetadataWidgetSetting", "开发ing"))
        self.auto_button.setText(_translate("MetadataWidgetSetting", "自动补全元数据"))
        self.label_2.setText(_translate("MetadataWidgetSetting", "将会对载入的还未进行补全的文件\n"
"进行补全"))
        self.sure_button.setText(_translate("MetadataWidgetSetting", "确定设置"))
