# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AutoMetadataDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AutoMetadataDialog(object):
    def setupUi(self, AutoMetadataDialog):
        AutoMetadataDialog.setObjectName("AutoMetadataDialog")
        AutoMetadataDialog.resize(389, 125)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(4)
        AutoMetadataDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(AutoMetadataDialog)
        self.verticalLayout.setSpacing(14)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(AutoMetadataDialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(AutoMetadataDialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(6)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.buttonBox = QtWidgets.QDialogButtonBox(AutoMetadataDialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AutoMetadataDialog)
        self.buttonBox.accepted.connect(AutoMetadataDialog.accept)
        self.buttonBox.rejected.connect(AutoMetadataDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AutoMetadataDialog)

    def retranslateUi(self, AutoMetadataDialog):
        _translate = QtCore.QCoreApplication.translate
        AutoMetadataDialog.setWindowTitle(_translate("AutoMetadataDialog", "自动补全ing"))
        self.label.setText(_translate("AutoMetadataDialog", "正在为你自动补全元数据"))
